<?php
/**
 * TinRequestResultSharedModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TinCorrect.Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TinRequestResultSharedModelTest Class Doc Comment
 *
 * @category    Class */
// * @description TinRequestResultSharedModel
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TinRequestResultSharedModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TinRequestResultSharedModel"
     */
    public function testTinRequestResultSharedModel()
    {
    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "tin"
     */
    public function testPropertyTin()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "irs_result_id"
     */
    public function testPropertyIrsResultId()
    {
    }

    /**
     * Test attribute "result_description"
     */
    public function testPropertyResultDescription()
    {
    }

    /**
     * Test attribute "result_category"
     */
    public function testPropertyResultCategory()
    {
    }

    /**
     * Test attribute "request_date"
     */
    public function testPropertyRequestDate()
    {
    }
}
